env: "test"

grpc_server:
  address: "0.0.0.0"
  port: 50052

database:
  username: "postgres"
  password: "admin"
  host: "auth-db-test"
  port: "5432"
  db_name: "authservice_test"
  migrations_path: "./migrations"

jwt:
  secret: "my-secret"
  access_expires_at: "1m"
  refresh_expires_at: "10m"

user_service:
  address: "user-service-test"
  port: 50051

prometheus:
  address: "0.0.0.0"
  port: 9102
