env: "test"

api:
  base_url: "http://localhost:42080/api"
  timeout: "10s"
  client_id: "e2e-test-client"
  client_secret: "e2e-test-secret"


test:
  concurrent: 5
  requests_per_test: 100
  test_timeout: "2m"
  cleanup: true
  log_level: "info"

services:
  user_service:
    address: "localhost"
    port: 42051
  auth_service:
    address: "localhost"
    port: 42052
  post_service:
    address: "localhost"
    port: 42053
  relation_service:
    address: "localhost"
    port: 42054
  notification_service:
    address: "localhost"
    port: 42055

jwt:
  secret: "my-secret"
  access_expires_at: "60m"
  refresh_expires_at: "6000m"


